default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
    api_key = app_store_connect_api_key
    git_pull(only_tags: true)
    increment_build_number({build_number: latest_testflight_build_number(api_key: api_key) + 1})
    match
  end

  # Lanes
  desc "Push a new prod build to TestFlight"
  lane :prod do
    build_app(configuration: "Release", silent: true)
  end

  desc "Push a new staging build to TestFlight"
  lane :staging do
    build_app(configuration: "Debug", silent: true)
  end

  after_all do
    changelog_from_git_commits
    lane = (lane_context[SharedValues::LANE_NAME] == "ios prod" ? "Prod" : "Staging")
    changelog = "Build " + lane + ": \n" + lane_context[SharedValues::FL_CHANGELOG]
    upload_to_testflight(changelog: changelog)
     if lane == "Prod"
        add_git_tag(tag: version, build_number: build_number, message: changelog)
        push_git_tags
     end
  end

  # Getter
  def version
    get_version_number
  end

  def build_number
    get_build_number
  end
end